### ISSUE TITLE
Repetition of the results

### ISSUE THREAD

**Issue by bortzmeyer** [letoams/hash-slinger#10]
Why repeating the same line?

% tlsa --verify nohats.ca  
SUCCESS (usage 3): The certificate offered by the server matches the TLSA record
SUCCESS (usage 3): The certificate offered by the server matches the TLSA record

% tlsa --verify  www.bortzmeyer.org  
SUCCESS (usage 2): A certificate in the certificate chain (including the end-entity certificate) offered by the server matches the TLSA record
SUCCESS (usage 2): A certificate in the certificate chain (including the end-entity certificate) offered by the server matches the TLSA record
SUCCESS (usage 2): A certificate in the certificate chain (including the end-entity certificate) offered by the server matches the TLSA record

**Comment by letoams** [comment]
On Sat, 17 Oct 2015, Stéphane Bortzmeyer wrote:

> Why repeating the same line?
> 
> % tlsa --verify nohats.ca
> 
> SUCCESS (usage 3): The certificate offered by the server matches the TLSA record
> SUCCESS (usage 3): The certificate offered by the server matches the TLSA record

One for all A/AAAA records. Guess we could show that better :)

Paul

**Comment by letoams** [comment]
this is fixed in git and will be in 2.7. It will show the IP addresses so you can figure out which of your servers is broken :)
