### ISSUE TITLE
hash-slinger needs to be rebuilt on Fedora 30

### ISSUE THREAD

**Issue by jduprat** [letoams/hash-slinger#23]
I am running into issue #20 on Fedora 30.
https://github.com/letoams/hash-slinger/issues/20

The package is old:
hash-slinger-2.7-8.fc29.noarch
Build Date  : Fri 13 Jul 2018 05:46:17 PM PDT

It was not rebuilt for f30:
https://src.fedoraproject.org/rpms/hash-slinger/c/01bfb06d703099e74289cf5825b88b813e8862ec?branch=master

Can we trigger a rebuild of the Fedora package?

JL

**Comment by jduprat** [comment]
See also https://bugzilla.redhat.com/show_bug.cgi?id=1723905

**Comment by frankcrawford** [comment]
There are going to be two issues with the current release, firstly, all the scripts need to specify a specific python version for Fedora 30, i.e. they should be /usr/bin/python2.
Secondly from Fedora 31 (due within weeks) Python2 will be deprecated, and it is expected to be Python3 only.
The best step is to bite the bullet and go to Python3 now.

**Comment by hgshoggins** [comment]
Current `master` successfully tested on a Fedora 31 machine with Python3.

**Comment by jduprat** [comment]
Confirm that top-of-tree master works for me on Fedora 31.  Thank you!
