### ISSUE TITLE
python2 to python3

### ISSUE THREAD

**Issue by Cherkah** [letoams/hash-slinger#24]
not an issue
all dependencies are python2. does hash-slinger will refresh  to python3?

thank for your work

**Comment by stoecker** [comment]
I started a bit, but had not time to continue. Some things can be changed, so code supports python2 and python3, other things are python3 specific and need a 2/3 switch at the start of the tool.

Patches/Pull requests are welcome.

**Comment by frankcrawford** [comment]
Are you sure you really want to continue supporting Python2?  It will just make the code more complicated and messy if you try and do both at once.
Given this project only moves slowly it would be simpler to just draw a line and say the current version is the last Python2, and all going forward will be Python3.
I'm happy to submit a PR for the upgrade to Python3.

**Comment by stoecker** [comment]
That would be fine. openSUSE also already deprecated python2. A complete switch to python3 would be fine. If you do the conversion I happily accept a submission.

**Comment by letoams** [comment]
That would work for me

**Comment by stoecker** [comment]
Fixed

**Comment by stoecker** [comment]
I did update the remaining files (with a bit trouble, seems I need to wakeup first :-) for a release on Sunday. I think that should be enough time to find small troubles...
