### ISSUE TITLE
Python3 errors

### ISSUE THREAD

**Issue by hgshoggins** [letoams/hash-slinger#29]
I guess lots of things have changed since porting happened with Python3. When using `tlsa`, I now get an error:
`Could not verify local certificate: endswith first arg must be bytes or a tuple of bytes, not str.`

**Comment by stoecker** [comment]
With last release or master? If with master, please tell the commandline you use.

**Comment by hgshoggins** [comment]
It's master, with the following command:
```bash
/usr/bin/tlsa --create --selector 1 --mtype 2 --certificate /path/to/certificate.pem www.fqdn.tld
```

**Comment by stoecker** [comment]
Thanks for the report.
