### ISSUE TITLE
Output showing same result twice instead of two different (RSA/ECDSA) records

### ISSUE THREAD

**Issue by offerman** [letoams/hash-slinger#33]
Running version 3.0, I get the same hash twice on a system that provides two TLSA mail records (one for RSA, another one for ECDSA):

```
[root@services hash-slinger-master]# ./tlsa --create --port 25 --starttls smtp --output rfc  offerman.com
Got a certificate with Subject: /C=NL/ST=Zuid-Holland/L=Haaglanden/O=Offerman Consulting/OU=Postfix SSL key/CN=mail.offerman.net/emailAddress=postmaster@offerman.net
_25._tcp.offerman.com. IN TLSA 3 0 1 c35bc60d645714709632bc43a688a6fe402e96b341a412228f654c9006e98373
Got a certificate with Subject: /C=NL/ST=Zuid-Holland/L=Haaglanden/O=Offerman Consulting/OU=Postfix SSL key/CN=mail.offerman.net/emailAddress=postmaster@offerman.net
_25._tcp.offerman.com. IN TLSA 3 0 1 c35bc60d645714709632bc43a688a6fe402e96b341a412228f654c9006e98373
```

Checking the certificates provided using testssl does show the two certificates correctly:

```
 Server Certificate #1
   Signature Algorithm          SHA512 with RSA
   Server key size              RSA 4096 bits
   Server key usage             --
   Server extended key usage    --
   Serial / Fingerprints        4051FECCC26BB2E8BC2C2A4BE33C33CE0DABFADB / SHA1 3875BF5F54014F1F997A8CF51488B635BBD023B6
                                SHA256 E66A38B41291CBEF4F7F3305F94C96F80568F3583D871427E5EE4C5CFB686255

 Server Certificate #2
   Signature Algorithm          ECDSA with SHA512
   Server key size              EC 256 bits
   Server key usage             --
   Server extended key usage    --
   Serial / Fingerprints        14AF1CF4FECAB081A5791A0B32000FC9DA3A91FE / SHA1 8BD02023C602083010AC7D4864394A985B136509
                                SHA256 C35BC60D645714709632BC43A688A6FE402E96B341A412228F654C9006E98373
```

**Comment by stoecker** [comment]
That's because this server has IPv4 and IPv6 address (i.e. two addresses). You get that output for both (they could be and sometimes are different).

Probably we could add a suppression in case the output is identical for multiple IP addresses or at least output the addresses.

**Comment by offerman** [comment]
Ah, got it! Just tried the -4 and -6 options, which indeed give me only one record.

It would be nice to suppress the second one or make clear what's going on in the output somehow, as there are no hints on this in the man page, and I assume that the both are equal in most cases.

Specifically for the '--create' option I think it would make sense to do both suppression and clarification, as there is no use in producing the same record twice, thereby forcing people to take a closer look at the two to see whether they are different or not. That would suggest always adding the IP-address to the preceding comment if the two hashes are different, and suppress (i.e. collapse) the second hash and add both the IPv4 and IPv6 address to the comment in case the two are the same.

And since this would involve changing the comment line anyway, maybe it should be preceded by a '; ' prefix to make it a real zone file comment.

The question that remains: why isn't the hash for the RSA-based certificate being produced as well?

**Comment by offerman** [comment]
Ah, got it! Just tried the -4 and -6 options, which indeed give me only one record.

It would be nice to suppress the second one or make clear what's going on in the output somehow, as there are no hints on this in the man page, and I assume that the both are equal in most cases.

Specifically for the '--create' option I think it would make sense to do both suppression and clarification, as there is no use in producing the same record twice, thereby forcing people to take a closer look at the two to see whether they are different or not. That would suggest always adding the IP-address to the preceding comment if the two hashes are different, and suppress (i.e. collapse) the second hash and add both the IPv4 and IPv6 address to the comment in case the two are the same.

And since this would involve changing the comment line anyway, maybe it should be preceded by a '; ' prefix to make it a real zone file comment.

The question that remains: why isn't the hash for the RSA-based certificate being produced as well?

**Comment by offerman** [comment]
Ah, got it! Just tried the -4 and -6 options, which indeed give me only one record.

It would be nice to suppress the second one or make clear what's going on in the output somehow, as there are no hints on this in the man page, and I assume that the both are equal in most cases.

Specifically for the '--create' option I think it would make sense to do both suppression and clarification, as there is no use in producing the same record twice, thereby forcing people to take a closer look at the two to see whether they are different or not. That would suggest always adding the IP-address to the preceding comment if the two hashes are different, and suppress (i.e. collapse) the second hash and add both the IPv4 and IPv6 address to the comment in case the two are the same.

And since this would involve changing the comment line anyway, maybe it should be preceded by a '; ' prefix to make it a real zone file comment.

The question that remains: why isn't the hash for the RSA-based certificate being produced as well?

**Comment by offerman** [comment]
Ah, got it! Just tried the -4 and -6 options, which indeed give me only one record.

It would be nice to suppress the second one or make clear what's going on in the output somehow, as there are no hints on this in the man page, and I assume that the both are equal in most cases.

Specifically for the '--create' option I think it would make sense to do both suppression and clarification, as there is no use in producing the same record twice, thereby forcing people to take a closer look at the two to see whether they are different or not. That would suggest always adding the IP-address to the preceding comment if the two hashes are different, and suppress (i.e. collapse) the second hash and add both the IPv4 and IPv6 address to the comment in case the two are the same.

And since this would involve changing the comment line anyway, maybe it should be preceded by a '; ' prefix to make it a real zone file comment.

The question that remains: why isn't the hash for the RSA-based certificate being produced as well?

**Comment by offerman** [comment]
Ah, got it! Just tried the -4 and -6 options, which indeed give me only one record.

It would be nice to suppress the second one or make clear what's going on in the output somehow, as there are no hints on this in the man page, and I assume that the both are equal in most cases.

Specifically for the '--create' option I think it would make sense to do both suppression and clarification, as there is no use in producing the same record twice, thereby forcing people to take a closer look at the two to see whether they are different or not. That would suggest always adding the IP-address to the preceding comment if the two hashes are different, and suppress (i.e. collapse) the second hash and add both the IPv4 and IPv6 address to the comment in case the two are the same.

And since this would involve changing the comment line anyway, maybe it should be preceded by a '; ' prefix to make it a real zone file comment.

The question that remains: why isn't the hash for the RSA-based certificate being produced as well?

**Comment by offerman** [comment]
Ah, got it! Just tried the -4 and -6 options, which indeed give me only one record.

It would be nice to suppress the second one or make clear what's going on in the output somehow, as there are no hints on this in the man page, and I assume that the both are equal in most cases.

Specifically for the '--create' option I think it would make sense to do both suppression and clarification, as there is no use in producing the same record twice, thereby forcing people to take a closer look at the two to see whether they are different or not. That would suggest always adding the IP-address to the preceding comment if the two hashes are different, and suppress (i.e. collapse) the second hash and add both the IPv4 and IPv6 address to the comment in case the two are the same.

And since this would involve changing the comment line anyway, maybe it should be preceded by a '; ' prefix to make it a real zone file comment.

The question that remains: why isn't the hash for the RSA-based certificate being produced as well?

**Comment by offerman** [comment]
Ah, got it! Just tried the -4 and -6 options, which indeed give me only one record.

It would be nice to suppress the second one or make clear what's going on in the output somehow, as there are no hints on this in the man page, and I assume that the both are equal in most cases.

Specifically for the '--create' option I think it would make sense to do both suppression and clarification, as there is no use in producing (->adding) the same record twice, thereby forcing people to take a closer look at the two to see whether they are different or not. That would suggest always adding the IP address to the preceding comment if the two hashes are different, and suppress (i.e. collapse) the second hash and add both the IPv4 and IPv6 address to the comment in case the two are the same.

And since this would involve changing the comment line anyway, maybe it should be preceded by a '; ' prefix to make it a real zone file comment?

The question that remains: why isn't the hash for the RSA-based certificate being produced as well?
