### ISSUE TITLE
not calling m2crypto in Debian Python 3 (script 3.1) 

### ISSUE THREAD

**Issue by Michael-MCP** [letoams/hash-slinger#34]
I have two systems, one (ubuntu AMD64) would run (version 2.7) on python 2 the other (Ubuntu ARM64) would not run either version (of the script) on either version (of python). 
below running version 3.1 copied from latest Git source on python 3:

ARM:
```
python3 tlsa3.1.py --create --port 443 --protocol tcp --certificate /etc/letsencrypt/live/example.com/cert.pem --usage 3 --selector 1 --mtype 1 example.com
Could not verify local certificate: name 'BIO' is not defined.
```
Libraries:

- python-m2crypto/oldstable,now 0.24.0-1.1 amd64 [installed,automatic]
- python-dnspython/oldstable,now 1.15.0-1+deb9u1 all [installed,automatic]
- python-gnupg/oldstable,now 0.3.9-1 all [installed,automatic]

AMD:
```
Traceback (most recent call last):
  File "tlsa3.1.py", line 34, in <module>
    from M2Crypto import X509, SSL, BIO, m2
ImportError: No module named 'M2Crypto'
```
Libraries:

- python-dnspython/stable,now 1.16.0-1 all [installed,automatic]
- python-gnupg/stable,now 0.4.4-1 all [installed,automatic]
- python-m2crypto/stable,now 0.31.0-4+deb10u1 armhf [installed,automatic]

However I have/had m2crypto library on both of these systems. 
Again this was running the latest (3.1) code from GitHub in python3.

----------------------------------
looking back at the 2.7 version....
this was running fine until I updated my (Ubuntu AMD64)python2.7 libraries now neither machine or version of python will run. 

what libraries changed on the update (Ubuntu AMD64) ?

- python-cryptography (1.7.1-3+deb9u2)
- libpython2.7-minimal:amd64 (2.7.13-2+deb9u4)
- libpython2.7-stdlib:amd64 (2.7.13-2+deb9u4)
- python2.7-minimal (2.7.13-2+deb9u4)
- python2.7 (2.7.13-2+deb9u4)

Previously:

- libpython-stdlib/stable,now 2.7.13-2 amd64 [installed,automatic]
- libpython2.7/stable,stable,now 2.7.13-2+deb9u3 amd64 [installed,automatic]
- libpython2.7-minimal/stable,stable,now 2.7.13-2+deb9u3 amd64 [installed,automatic]
- libpython2.7-stdlib/stable,stable,now 2.7.13-2+deb9u3 amd64 [installed,automatic]
- python/stable,now 2.7.13-2 amd64 [installed]
- python-crypto/stable,now 2.6.1-7 amd64 [installed,automatic]
- python-cryptography/stable,now 1.7.1-3 amd64 [installed,auto-removable]
- python-dnspython/stable,now 1.15.0-1+deb9u1 all [installed,automatic]
- python-gnupg/stable,now 0.3.9-1 all [installed,automatic]
- python-m2crypto/stable,now 0.24.0-1.1 amd64 [installed,automatic]
- python-openssl/stable,now 16.2.0-1 all [installed,auto-removable]

I see this was already raised and marked as fixed in https://github.com/letoams/hash-slinger/issues/20  but the new code is for python3, so have opened a new ticket.

**Comment by stoecker** [comment]
I'd expect there should be a python3-m2crypto to let the current python3 version work. At least that's what I have on openSUSE and Ubuntu uses the same naming.
