### ISSUE TITLE
The `hostname` command line parameter does not matter

### ISSUE THREAD

**Issue by andrejpodzimek** [letoams/hash-slinger#35]
The `hostname` command line parameter does nothing, can be set to `whatever.random.string` (instead of the actual domain) and nobody+nothing cares. It should not be required.

It might make sense for records other than `1 0 2` and `3 0 2`, maybe, but in that case it should only be required when it matters.

**Comment by stoecker** [comment]
I don't know what you're talking about. How should the tlsa tool wok without specifying a domain name? Should it guess what you want?

Also for local files the hostname is relevant, as the verification and output depend on the name.
