### ISSUE TITLE
hash-slinger available for Fedora and EPEL

### ISSUE THREAD

**Issue by frankcrawford** [letoams/hash-slinger#37]
Just a note that hash-slinger has unretired for Fedora and EPEL and will shortly be available for Fedora 34 & 35 and for EPEL 8 and 9.

It is currently available in Fedora rawhide, and an old version is in EPEL 7.

**Comment by letoams** [comment]
On Sat, 15 Jan 2022, Frank Crawford wrote:

> Just a note that hash-slinger has unretired for Fedora and EPEL and will shortly be available for Fedora 34 & 35 and for EPEL 8 and 9.

Thanks! I appreciate the work you did!

**Comment by stoecker** [comment]
I merged the related pull request.

**Comment by frankcrawford** [comment]
I'll push an updated spec file, as there were a few final changes that I did to improve it.
