### ISSUE TITLE
openpgpkey -f does not work on fedoraproject keys

### ISSUE THREAD

**Issue by pemensik** [letoams/hash-slinger#39]
I have tested it just briefly. But it does not seem be able to download PGP key. Is that intentional? Can it even be fixed?

What I tried:
```
$ openpgpkey -f fedora-36-primary@fedoraproject.org 
openpgpkey: Received OpenPGP data does not contain a key with keyid fedora-36-primary@fedoraproject.org
(add --uid <uid> to override with any of the below received uids)
# Fedora (36) <fedora-36-primary@fedoraproject.org>

$ openpgpkey -v fedora-36-primary@fedoraproject.org 
All OPENPGPKEY records matched with content from the local keyring
```

Is UID required in received data, when I have explicitly provided it to the tool? It might have changed with some gnupg change. Is that fixable?

Using ``hash-slinger-3.1-2.fc34.noarch``

**Comment by pemensik** [comment]
Even example from man page does not anymore: ``openpgpkey --fetch paul@nohats.ca``

**Comment by stoecker** [comment]
You need to add --uid "Fedora (36)". Seems an additional security mechanism. But it's strange that --uid F also works.

**Comment by pemensik** [comment]
I am not sure why it does require it, but if I use ``openpgpkey -f --uid fedora-36-primary fedora-36-primary@fedoraproject.org`` or ``openpgpkey -f --uid paul paul@nohats.ca``, then I can fetch it successfully. Could it use as --uid value the user part automatically?

**Comment by stoecker** [comment]
I think that mechanism is to prevent loading wrong key from the server, as nowadays there are so many fake keys. Thought it seems not to work as I would expect it to work.

**Comment by pemensik** [comment]
loading wrong from the server? What do you mean? We have DNSSEC for a strong cryptographic protection, yet we rely on such annoying protection? What does it protect from? User adoption?

**Comment by stoecker** [comment]
Ah, sorry. I thought that fetches the entry from a PGP key server. It fetches it from DNS. Well, then I don't understand the additional check. Have to look at the history of the code...

**Comment by stoecker** [comment]
https://github.com/letoams/hash-slinger/commit/0c6d8fd344d1c559ee5e712163de9b5dfc5151fa
Seems there was a mixup in this change.

**Comment by pemensik** [comment]
Sure, line 142 has to be put back. Those options even do not make sense for fetch or verify, but it requires them by mistake.

**Comment by pemensik** [comment]
A changelog entry would now hurt, think this is issue worth mentioning

**Comment by paulwouters** [comment]
It seems the --fetch breaks it?

This works fine:
openpgpkey paul@nohats.ca
openpgpkey pwouters@fedoraproject.org

oops, update: that just pulls it from my local keyring :)

**Comment by paulwouters** [comment]
For --fetch, it seems that the email address does not match because the gpg key expects the full name plus email address ?
Perhaps it should be looking for X@Y within each uid? (and confirm there is only one "@" in the string?

It looks like the gpgnet.export_keys() might have changed how it handles arguments ?

note that on failure to fetch by email, it dumps a list of uids you can use:

$ openpgpkey --fetch paul@nohats.ca 
openpgpkey: Received OpenPGP data does not contain a key with keyid paul@nohats.ca
(add --uid <uid> to override with any of the below received uids)
\# Paul Wouters (online key) <paul@nohats.ca>


but 'Paul Wouters (online key) <paul@nohats.ca>' is not 'paul@nohats.ca'

**Comment by paulwouters** [comment]
oops yes the one line removed is the error. Although it seems fedoraproject.org removed all the OPENPGPKEY records :P

**Comment by pemensik** [comment]
It does fetch something to me: ``openpgpkey --fetch --uid f fedora-36-primary@fedoraproject.org``. Just rawhide key is not published. Why do you think they removed all those records?

**Comment by pemensik** [comment]
Manual page mentions --uid and --keyid only for create, which does make sense indeed. I don't think it is useful for anything in verify or fetch mode.

**Comment by paulwouters** [comment]
I think it makes sense to check that the email address used for pulling the key is a valid key id on the key pulled. But matching should be done so it ignores full name and just extracts the email address for comparison.

Sent using a virtual keyboard on a phone

**Comment by stoecker** [comment]
Anything left to do?

**Comment by pemensik** [comment]
A bugfix release maybe?

**Comment by stoecker** [comment]
Done.
