### ISSUE TITLE
man page: Create and verify RFC-TBD OPENPGPKEY DNS records

### ISSUE THREAD

**Issue by pemensik** [letoams/hash-slinger#40]
Because the [RFC 7929](https://datatracker.ietf.org/doc/rfc7929/) is already accepted, it should be updated in man page. Also in SEE ALSO.

**Comment by pemensik** [comment]
MR #31 were not complete. Consider updating also url from people.redhat.com to github here, in SEE ALSO page of openpgpkey.

**Comment by pemensik** [comment]
Also rpm spec description contains reference to draft only:

```
sshfp       Generate RFC-4255 SSHFP DNS records from known_hosts files
            or ssh-keyscan
tlsa        Generate RFC-6698  TLSA DNS records via TLS
openpgpkey  Generate draft-ietf-dane-openpgpkey DNS records from OpenPGP
            keyrings
ipseckey    Generate RFC-4025 IPSECKEY DNS records on Libreswan
````

**Comment by stoecker** [comment]
Fixed (with wrong ticket id :-)
