### ISSUE TITLE
option rfc is not working correct

### ISSUE THREAD

**Issue by smindorf** [letoams/hash-slinger#5]
Hi,
I've setup a docker container running bind 9.9.7. 
On my System (Ubuntu 14.04) I've cloned your repository.
No I've created a TYPE61 record:

``` bash
./openpgpkey --output rfc soeren@example.com

```

I get a Record and I put this record in my zone.
After I've done it I query my zone and get a differnt Key, not my public key. I get one key of my contacts in the gpg keystore.

If I use **output generic** all is right.

I've verified it with

``` bash
dig @localhost -p 49153 +short -t type61 $(
    printf "%s._openpgpkey.example.com" $(
        printf "%s" soeren |
        openssl dgst -sha224  -binary |
        hexdump -ve '/1 "%02x"'
        )
    ) |
    perl -ane '
        ($escape_sharp, $len) = splice(@F, 0, 2);
        next if ($escape_sharp ne q{\#}); 
        ($rdata = join("", @F)) =~ s/(..)/chr(hex($1))/eg;
        next if (length($rdata) != $len);
        print $rdata;
        last;
        ' |
    gpg --import --dry-run --verbose
```

because I use bind in a docker for testing.

I've also installed 

```
python-gnupg_0.3.7-1_all.deb
```

Regards,
Soeren

**Comment by letoams** [comment]
On Wed, 18 Mar 2015, smindorf wrote:

> Subject: [hash-slinger] option rfc is not working correct (#5)

I've confirmed the bug. Will look into it.

Paul

**Comment by smindorf** [comment]
Hi Paul,

did you have any news?

Regards,
Soeren

**Comment by letoams** [comment]
I cannot reproduce this anymore with the current version. Are you still seeing an issue?

**Comment by smindorf** [comment]
Hi Paul,

no it seem to be soved.

Thanks
Soeren
