### ISSUE TITLE
doesn't work for me....

### ISSUE THREAD

**Issue by thigazi** [letoams/hash-slinger#6]
Hi people,
I made a git checkout of your version and installed globally on my system all the libraries needed.
Now I want to generate the OPENPGP RR record with:

tamer@tux ~/Downloads/hash-slinger-2.6 $ openpgpkey -c sample-address@gmx.de

and I get this answer:
No key found containing the email address 'sample-address@gmx.de' in the keyid(s)

But when I execute:
tamer@tux ~/Downloads/hash-slinger-2.6 $ gpg --list-key sample-address@gmx.de

I get my key showed.
pub   4096R/24464FC4 2014-08-23 [verfällt: 2019-08-22]
uid       [ uneing.] Tamer Higazi sample-address@gmx.de
sub   4096R/CFBF4422 2014-08-23 [verfällt: 2019-08-22]

what did I make wrong ?!

Best, Tamer

**Comment by letoams** [comment]
On Sun, 22 Mar 2015, Tamer Higazi wrote:

> I made a git checkout of your version and installed globally on my system all the libraries needed.
> Now I want to generate the OPENPGP RR record with:
> 
> tamer@tux ~/Downloads/hash-slinger-2.6 $ openpgpkey -c tamer.higazi@gmx.de
> 
> and I get this answer:
> No key found containing the email address 'tamer.higazi@gmx.de' in the keyid(s)
> 
> But when I execute:
> tamer@tux ~/Downloads/hash-slinger-2.6 $ gpg --list-key tamer.higazi@gmx.de
> 
> I get my key showed.
> pub 4096R/24464FC4 2014-08-23 [verfällt: 2019-08-22]
> uid [ uneing.] Tamer Higazi tamer.higazi@gmx.de
> sub 4096R/CFBF4422 2014-08-23 [verfällt: 2019-08-22]
> 
> what did I make wrong ?!
> 
> Best, Tamer

Can you email me (paul@nohats.ca) your public key or upload it to a key
server? I did not see a 4096 bit key with that email address on the
key server.

Paul

**Comment by thigazi** [comment]
Here is the key (link expires in 1 week):
http://pastebin.com/raw.php?i=6sztQGdr

imported it in keyring and executed:

tamer@tux ~ $ openpgpkey -c tamer.higazi@gmx.de
No key found containing the email address 'tamer.higazi@gmx.de' in the 
keyid(s)

best, Tamer

Am 23.03.2015 um 07:10 schrieb Paul Wouters (libreswan):

**Comment by thigazi** [comment]
seemst to work now.... I don't know why.
crazy....

I made a complete gentoo system update.....

Thanks again!

best, Tamer

Am 23.03.2015 um 19:14 schrieb Tamer Higazi:

**Comment by letoams** [comment]
Thanks for letting me know
